name: Uptime Check

on:
  schedule:
    - cron: '0 * * * *'  # Runs every day at 12:00 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  check_urls:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - "https://toilet.football"
          - "https://new.toilet.football"
          - "https://winokan.com"
          # - "https://foosball.winokan.com"
    
    name: Check ${{ matrix.url }}  # This makes each job name unique

    steps:
      - name: Check URL
        run: |
          echo "Checking ${{ matrix.url }}..."
          status_code=$(curl -o /dev/null -s -w "%{http_code}" "${{ matrix.url }}")
          if [[ "$status_code" -ne 200 ]]; then
            echo "::error title=URL Check Failed::URL ${{ matrix.url }} returned status $status_code"
            exit 1
          fi

